version: '3.7'

services:
  mongo:
    image: mysql
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - '3307:3306'
    environment:
        MYSQL_DATABASE: felipedb
        MYSQL_ROOT_PASSWORD: root
